# Asteroid constants
ASTEROID_SCORE_MULTIPLIER = 2.3
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MAX_SPAWNED = 25
ASTEROID_EXPLOSION_RADIUS = 3
ASTEROID_EXPLOSION_VELOCITY = 150

# Player Constants
PLAYER_RADIUS = 20
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_SHOOT_SPEED = 500
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300
SHOT_RADIUS = 5

# Misc Constants
LINE_WIDTH = 2
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
